#!/usr/bin/python3
import concurrent.futures
import os
import time
import requests
from sys import argv
from urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)
start_time = time.time()

try:
    filename = argv[1]
    urls = []

    def appendUrl(filename):
        with open(filename, 'r') as f:
            for url in f:
                url = url.strip()
                urls.append(url)
            
    appendUrl(filename)


    def getStatus(url):
        r = requests.get(url, allow_redirects=False, timeout=3, verify=False)
        print(f'{url} [{r.status_code}]')


    with concurrent.futures.ThreadPoolExecutor() as executor:
            executor.map(getStatus, urls)    

except IndexError as e:
    print('Usage:')
    print(f'{argv[0]} <urls.txt>')
